export const NOTIFICATION_TASKS_GENERATE = 'NOTIFICATION_TASKS_GENERATE'
export const NOTIFICATION_TASK_SET = 'NOTIFICATION_TASK_SET'
export const NOTIFICATION_TASKS_CLEAR = 'NOTIFICATION_TASKS_CLEAR'
