export const NOTIFICATION_TASKS_GENERATE = 'NOTIFICATION_TASKS_GENERATE'
export const NOTIFICATION_TASKS_PUSH = 'NOTIFICATION_TASK_SET'
export const NOTIFICATION_TASKS_CLEAR = 'NOTIFICATION_TASKS_CLEAR'
export const NOTIFICATION_TASKS_STATUS_SET = 'NOTIFICATION_TASKS_STATUS_SET'
