export const USER_START_ONBOARDING = 'USER_START_ONBOARDING'
export const USER_VIEWED_MODAL = 'USER_VIEWED_MODAL'
export const USER_JUST_REGISTERED_TOGGLE = 'USER_JUST_REGISTERED_TOGGLE'
export const RESET_ONBOARDING_STATE = 'RESET_ONBOARDING_STATE'
